[package]
name = "epithet"
version = "0.1.0"
edition = "2024"
authors = ["Brian McCallister <brianm@skife.org>"]
license = "Apache-2.0"


[dependencies]
clap = { version = "4.4", features = ["derive"] }
directories = "6.0.0"
futures = "0.3.31"
tokio = { version = "1", features = ["full"] }
